parent: "configs/scannet_base.yaml"
save_step: 100

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "data/scannet/scene0169_00"
save_path: "output/dataset/scannet/scene0169_00"
